### ISSUE TITLE
A small problem

### ISSUE THREAD

**Issue by luzhu123** [PacktPublishing/Spring-Security-Third-Edition#1]
Hi!  Vibhuti4389:
I have purchased the book ,very nice! But I find that the source code build by gradle,not farmiliar with gradle.
Can you transfer gradle to maven ,if I use gradle to build the project ,many problems occurs! thank you

**Comment by tomduffey** [comment]
the gradle build seems to have some instant problems especially with tomcat - the directions in the book don't lead to a solution - just more frustration - i am willing to work with you on getting this running 

this is a short description of the problem:

D:\jbcdcalendar\Chapter01\chapter01.00-calendar>d:\jbcdcalendar\gradlew.bat tomcatRun
Configuration on demand is an incubating feature.

> Task :chapter01:chapter01.00-calendar:compileJava
Note: D:\jbcdcalendar\Chapter01\chapter01.00-calendar\src\main\java\com\packtpub\springsecurity\web\configuration\AsyncDispatcherServlet.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :chapter01:chapter01.00-calendar:tomcatRun
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0

A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]

**Comment by luzhu123** [comment]
I have packed the code in the war ,when i put the war in the tomcat ,it can run ,but when i execute the command : tomcatRun ,the  embedded  tomcat throws exception.when i run the project , the exception is about the class:\src\main\java\com\packtpub\springsecurity\web\configuration\AsyncDispatcherServlet.java  too.
--



--

**Comment by luzhu123** [comment]
hi tomduffey:
does your project can run without any problems?

**Comment by wobblycogs** [comment]
I can confirm that when the project is packaged as a war and deployed in a stand alone Tomcat (version 8.5.14 in my case) it does indeed work. I built the war through Idea from the Gradle side window selecting Tasks > build > war.

If I try to run the projects using the method described in the book they **all** fail for various reasons (e.g. chapter 9 projects are importing things that aren't on the classpath). The chapter 1 failures are the same as described here and in various other bug reports.

**Comment by SpaceOso** [comment]
@wobblycogs where does the built war file end up?

**Comment by wobblycogs** [comment]
@SpaceOso on my system: _<path_to_intellij_project_folder>\Spring-Security-Third-Edition\Chapter01\chapter01.00-calendar\build\libs_

**Comment by SpaceOso** [comment]
@wobblycogs Thanks! So I'm able to run the html portion of it, none of the styles come through though...hmmm.

```
GET http://localhost:9090/webjars/bootstrap/css/bootstrap.min.css net::ERR_ABORTED
localhost/:19 GET http://localhost:9090/webjars/jquery/jquery.min.js net::ERR_ABORTED
localhost/:22 GET http://localhost:9090/css/styles.css net::ERR_ABORTED
localhost/:20 GET http://localhost:9090/webjars/bootstrap/js/bootstrap.min.js net::ERR_ABORTED
localhost/:22 GET http://localhost:9090/css/styles.css net::ERR_ABORTED
```

**Comment by kr601394** [comment]
> @wobblycogs Thanks! So I'm able to run the html portion of it, none of the styles come through though...hmmm.
> 
> ```
> GET http://localhost:9090/webjars/bootstrap/css/bootstrap.min.css net::ERR_ABORTED
> localhost/:19 GET http://localhost:9090/webjars/jquery/jquery.min.js net::ERR_ABORTED
> localhost/:22 GET http://localhost:9090/css/styles.css net::ERR_ABORTED
> localhost/:20 GET http://localhost:9090/webjars/bootstrap/js/bootstrap.min.js net::ERR_ABORTED
> localhost/:22 GET http://localhost:9090/css/styles.css net::ERR_ABORTED
> ```
1. add lines to build.gradle
    compile 'org.webjars:jquery:2.2.1'
    compile 'org.webjars:jquery-ui:1.11.4'
    compile 'org.webjars:bootstrap:3.3.6'

2. add lines to WebMvcConfig addResourceHandlers mothod
registry.addResourceHandler("/webjars/**").addResourceLocations("/webjars/").resourceChain(false);

good luck!

**Comment by ManikandanKurup-Packt** [comment]
Hi, I hope the issue has been resolved. If not, reopen this issue.
