### ISSUE TITLE
Chapter10/CAS.md says CAS is "Not done", when will it be done?

### ISSUE THREAD

**Issue by imaxwel** [PacktPublishing/Spring-Security-Third-Edition#2]
Looking forward to your reply a.s.a.p, thanks!

**Comment by imaxwel** [comment]
Meanwhile, this incomplete project is not listed in the TODOs.

**Comment by techsachinkumar** [comment]
Hi @imaxwel 

It seems the project is complete only. Could you try and check to see if there is any problem in it?
I think the CAS.md file is not updated.

Please have a look and let us know.

Regards
