### ISSUE TITLE
Missing class

### ISSUE THREAD

**Issue by wgorder** [PacktPublishing/Spring-Security-Third-Edition#3]
`Chapter03/chapter03.06-calendar/src/main/java/com/packtpub/springsecurity/configuration/SecurityConfig.java`

References a missing class

`import com.packtpub.springsecurity.web.authentication.DomainUsernamePasswordAuthenticationFilter;`

**Comment by ManikandanKurup-Packt** [comment]
Hi,
Please reopen the issue if the error hasn't been resolved yet.
