### ISSUE TITLE
Chapter01 compiles with error

### ISSUE THREAD

**Issue by IevhenIkonnykov** [PacktPublishing/Spring-Security-Third-Edition#4]
Hello,
I bought a book a few days ago and tried to launch the code of the Chapter one. Unfortunately it fails with the error:

 `org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'dataSource': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)`

I am new to Gradle, I expected to have a Maven project. I had some headache with having Gradle working and finally the project failed with the above mentioned error. Is there any ideas what it might be?

**Comment by SpaceOso** [comment]
Same issue.
